version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD:
      MINIO_BROWSER_REDIRECT_URL: https://minio.xxxxxxx.com.br
      MINIO_SERVER_URL: https://s3.xxxx.com.br
    volumes:
    - ./minio_data:/data
    ports:
    - 9000:9000
    - 9001:9001

